### ISSUE TITLE
Using hostname and ssh keys for remote log

### ISSUE THREAD

**Issue by vasiliosz** [guillermo-carrasco/bcbio-nextgen-monitor#42]
Thanks for sharing this nice tool!

With the log locally, everything works well. Also remotely, if I define the full host address, username and password in `~/.bcbio/monitor.yaml` - it works. 

I would like instead to just supply my hostname (i.e. `myhpchost`) to the config, and use the ssh keys already setup for password free authentication. 

Defining host in the config, without user/pass, does not work. In fact, it doesn't appear to connect to the remote even. 

```
server:
    SERVER_NAME: localhost:5000
    DEBUG: False
remote:
    host: myhpchost
log:
    level: INFO
```

Any ideas?

**Comment by guillermo-carrasco** [comment]
hi @vasiliosz ,

Thanks for opening this issue and sorry for the trouble. I apologise as well for the late reply, but I've been on vacation :).

Its strange, since within the code [I am loading the system keys](https://github.com/guillermo-carrasco/bcbio-nextgen-monitor/blob/master/bcbio_monitor/analysis/__init__.py#L80), so one would think it should work. 

Let me have a closer look and I'll come back to you when I figure out what's happening. 

Thanks again!

**Comment by guillermo-carrasco** [comment]
Hi @vasiliosz ,

I've been looking into this, and I can actually use the monitor with my ssh keys. Just to take this out of the way: Is your username in the remote host the same than your username locally? I'm asking because if not, you should at least specify your username in the configuration file. i.e my username locally is `guillem`, whilst my username in the remote server is `gcarrasco`, so my configuration file looks like this:

```
server:
    SERVER_NAME: localhost:5000
    DEBUG: False

remote:
    host: <remote server address>
    username: gcarrasco

log:
    level: INFO
```

I don't specify password, but I do have to specify username.

Lastly, can you ssh passwordless from a terminal? Had to ask :-)

Thanks for the patience!

**Comment by vasiliosz** [comment]
Thanks @guillermo-carrasco, 

It does work fine when I define the _full_ host adress and my username, without the password
I have short names for my hosts (`/etc/hosts`), and had given bcbio_monitor the short name only previously. 

Thanks for looking into it!

**Comment by guillermo-carrasco** [comment]
Hi @vasiliosz ,

You're welcome :-) 

Yeah I'm not sure how Paramiko, the library I'm using for SSH connection, handles aliases in `/etc/hosts`, apparently not very well :-/. Glad it works without password though :)

Cheers! And thanks for using `bcbio_monitor`!
